### ISSUE TITLE
[Feature]: MyBrand hubspot form - includes pricing calculations

### ISSUE THREAD

**Issue by mkirolos-safco** [Safco-Dental/Forms#102]
## Feature Request

**Title**: MyBrand hubspot form - includes pricing calculations

**Safco Employee Name**: Karyn Schaefges

**Safco Employee Email**: kschaefges@safcodental.com

**Department**: marketing

**Request Title**: MyBrand hubspot form - includes pricing calculations

**Short Description**:
 Need a hubspot form for MyBrand. Form will need to be completed by customer and contains functionality to calculate pricing when quantity is entered. The form will have a workflow to send lead to sales team (same workflow as the MyBrand Sample request). See attached excel spreadsheet.
https://safcodentalsupply-my.sharepoint.com/:x:/g/personal/monica_pearloralcare_com/EfH33ZGHlEdAm9PDbun2F2UB7Ab2F4r2WOe-aV-IzBY-oA?e=4DOblc&nav=MTVfezRGNEQwRjYyLUY5RkMtNENBNi1CQzlELTI4NzA5NDQ5NjdDQn0

**Benefits/Outcomes**: Ability for a customer to receive immediate pricing for mybrand toothbrush request since they are ready to place an order, while waiting for a sample request.

**Related Project**: main-website

**Priority**: medium

**Request Completion Date**: 2024-11-01

**Comment by mkirolos-safco** [comment]
https://www.safcodental.com/landing/mybrand-custom-toothbrushes-pricing/
This would be the page that the form will live in.

**Comment by shreyadhutiasafcodental** [comment]
Brainstorming needed - karyn will provide a workflow

**Comment by mkirolos-safco** [comment]
I just had a call with @kschaefges-safco , she will need to talk to Becky about the scope of this project since we believe that the requested excel sheet is not something that Hubspot can do out of the box.

**Comment by shreyadhutiasafcodental** [comment]
Discussed with Becky and Karyn - Closing issue!
