### ISSUE TITLE
[Bug]: Creating a new category for Clearnace (BCCCC)

### ISSUE THREAD

**Issue by mkirolos-safco** [Safco-Dental/Forms#104]
## Bug Report

**Title**: Creating a new category for Clearnace (BCCCC)

**Safco Employee Name**: Karyn Schaefges

**Safco Employee Email**: kschaefges@safcodental.com

**Date of Issue**: 0024-10-22

**Issue Headline**: other

**What happened**:
 Brad created a new category "Clearance" (BC) in the AS400 and added a clearance test item sku 2829102-C, this is a clearance section on the web. The category (BC) is not appearing in the content tool, nor are the super class (BCC) and the product class (BCCCC). We need Mario's assistance; this is similar to the new "Furniture" category we just created and added to the website.
These skus are open box returned products that we can resell and will be adding them as random when we receive. The clearance skus will have a "-C" extension.  When purchased sku will be marked as discontinued and dynamically fall off the website. 
Additionally, we discovered the "-C" sku also will appear in the regular product class where it will receive additional exposure. The products will be grouped within the product class under a group header "Open Box, Clearance". 
I've attached screen shots.

**Related Project**: main-website

**Priority**: high

**Customer Number or Email**: .

**Order Number**: .

**Browser of Issue**: 

**Steps to Reproduce**:
 On web: 
1. Search 2829102-C
2. Clearance item product class appears as well as the original class
3. Click on "Clearance Item" product class and results are the Dental Catalog" and not the product page.
4. The category, super category and product class do not appear in the content tool.

**Attached Files:**
https://api.safcodental.com/forms-submission/uploads/New_category_creation_-_Clearance.docx

**Comment by shreyadhutiasafcodental** [comment]
Fixed - check breadcrumbs

**Comment by kschaefges-safco** [comment]
@mkirolos-safco 
Below is the hierarchy, is this what you wanted?

Category = "Clearance" (BC)
SuperClass = "Safco Clearance" (BCC)
Product Class = "Clearance Items"  (BCCCC)

You will be checking on the breadcrumbs and why not added to the content tool.

**Comment by mkirolos-safco** [comment]
This is all set!
@kschaefges-safco  please confirm.

**Comment by kschaefges-safco** [comment]
@mkirolos-safco This looks good on the web. Bread crumbs are in sync. Just waiting to see in the content tool and you were working with Senica.

**Comment by kschaefges-safco** [comment]
@mariokirolos @mkirolos-safco This is appearing correctly on the web. We just need to get it updated in the content tools so we can use the grouping function within a product class when we have more skus added. Brad is on PTO this week, but will be adding more clearance skus to the product class.

**Comment by kschaefges-safco** [comment]
@mkirolos-safco Yesterday I added a search term "clearance" in the promotion application for class BCCCC and the app accepted the term, however when testing today using the search term nothing appears on the website. I will add the search term in the content tool after the class appears in that application and test. 

[clearance search term in promo application.docx](https://github.com/user-attachments/files/17437600/clearance.search.term.in.promo.application.docx)

**Comment by kschaefges-safco** [comment]
@mkirolos-safco @shreyadhutiasafcodental What is the status of this getting into the content tool? Last I understood Mario was working with Senica to get into the content tool and it is still not there. Also, the search term "clearance" will not return the BCCCC product class even after I added the search term in the promo application tool. I will also add to content tool once that has been updated/fixed. We are promoting clearance in November.

**Comment by mkirolos-safco** [comment]
@kschaefges-safco I am on the call now with LuAnn from Sceneca and Brad, LuAnn asked Brad to add to do one change on the AS400, and we expect that this will appear on the Content tool by tomorrow (after today's the end of day job is done).

**Comment by mkirolos-safco** [comment]
@kschaefges-safco , seems that it's working now
![Image](https://github.com/user-attachments/assets/ec23cba3-517b-40a7-85c5-4734fb660c86)

to ensure that we do not fall in the same issue again, we want to make sure that the new category is being added under the "WEB" category in order to appear in the Content Tool, LuAnn showed Brad how to do that in the Green Screen for reference.
