### ISSUE TITLE
[Bug]: Inventory status not updating

### ISSUE THREAD

**Issue by mkirolos-safco** [Safco-Dental/Forms#107]
## Bug Report

**Title**: Inventory status not updating

**Safco Employee Name**: Brad Joerger

**Safco Employee Email**: bjoerger@safcodental.com

**Date of Issue**: 2024-10-28

**Issue Headline**: other

**What happened**:
 We have had inventory in warehouse 1 since 10/16/24 for 5102611, 5102612, 5102613, and 5102614 but our website shows inventory status as "Backordered". Stock status on the website is based on warehouse 1 inventory so it should say "In stock". 

**Related Project**: main-website

**Priority**: high

**Customer Number or Email**: bjoerger@safcodental.com

**Order Number**: N.A

**Browser of Issue**: 

**Steps to Reproduce**:
 1 Go to website
2 Enter any of the above item numbers and you will see stock status shows backordered

**Comment by shreyadhutiasafcodental** [comment]
could be an issue from senica

**Comment by mkirolos-safco** [comment]
Jeong has reached out to Brad offline, I will mark this one as completed.
