### ISSUE TITLE
[Feature]: Product search query addition

### ISSUE THREAD

**Issue by mkirolos-safco** [Safco-Dental/Forms#108]
## Feature Request

**Title**: Product search query addition

**Safco Employee Name**: Karen 

**Safco Employee Email**: kchaefges@safcodental.com

**Department**: purchasing-product-development

**Request Title**: Acrylic Polishers / Fuzzies

**Short Description**:
 https://www.safcodental.com/catalog/finishing-and-polishing/abrasives-and-polishers/acrylic-polisher-wheel?ref=pcsrpr

These specific Meisinger products are called Fuzzies.  the industry refers to them as "fuzzies" we must add this search term to this product.  this should have been done when product was originally onboarded and I think it should be in the Product name.  Acrylic Polishing Wheel (Fuzzies) 
our competition already does this.  
Example:
https://meisingerusa.com/253f-250-hp-polisher-purple-used-on-acrylics-fuzzies-fine-25mm-hp-253f-250-hp

**Benefits/Outcomes**: Better product search / customer experience.  Potential increase in sales

**Related Project**: main-website

**Priority**: medium

**Request Completion Date**: 2024-11-07

**Comment by shreyadhutiasafcodental** [comment]
this is something that karyn might be able to do.

**Comment by mkirolos-safco** [comment]
@kschaefges-safco , is this something that we can do on the internal app?

**Comment by kschaefges-safco** [comment]
Yes, this can be done on the internal app. I will update.

**Comment by kschaefges-safco** [comment]
Completed and tested.
