### ISSUE TITLE
[Bug]: HubSpot search by account number 

### ISSUE THREAD

**Issue by mkirolos-safco** [Safco-Dental/Forms#40]
## Bug Report

**Title**: HubSpot search by account number 

**Safco Employee Name**: Maria Stockwell

**Safco Employee Email**: mstockwell@safcodental.com

**Date of Issue**: 2024-09-06

**Issue Headline**: other

**What happened**:
 When entering an account number in the search bar in HubSpot it is not pulling up the company or correct contact.

**Related Project**: other

**Priority**: medium

**Customer Number or Email**: mstockwell@safcodental.com

**Order Number**: N.A

**Browser of Issue**: 

**Steps to Reproduce**:
  Example search 86209, no company comes up, & contact take you to a different Safco acct #.

**Comment by shreyadhutiasafcodental** [comment]
investigation

**Comment by mkirolos-safco** [comment]
I had a call earlier today and showed @mariastockwell how to do the search with Customer number.
