### ISSUE TITLE
[Feature]: Programmatic ads Q4 - Add Belmont Universal Pixel to footer for tracking

### ISSUE THREAD

**Issue by mkirolos-safco** [Safco-Dental/Forms#90]
## Feature Request

**Title**: Programmatic ads Q4 - Add Belmont Universal Pixel to footer for tracking

**Safco Employee Name**: Karyn Schaefges

**Safco Employee Email**: kschaefges@safcodental.com

**Department**: marketing

**Request Title**: Add pixel to footer for Programmatic ads

**Short Description**:
 Running a Q4 Programmatic ads campaign and will need to have the Belmont Universal Pixel added to footer for tracking purposes. Launch is Oct 1 and/or sprint 4. Pixel is coming from the vendor and will be attached when received.

**Benefits/Outcomes**: Tracking the progress for the programmatic West Coast campaign.

**Related Project**: main-website

**Priority**: medium

**Request Completion Date**: 2024-10-01

**Comment by kschaefges-safco** [comment]
@mkirolos-safco 
Included is the universal pixel needed to be added to the site. Please place in the header to fire on all pages. 

If you need assistance let me know and we can set up a meeting with our third-party provider.

[Belmont - Safco Dental - Universal Pixel.txt](https://github.com/user-attachments/files/17033658/Belmont.-.Safco.Dental.-.Universal.Pixel.txt)

**Comment by mkirolos-safco** [comment]
@kschaefges-safco , noted, thanks.

**Comment by shreyadhutiasafcodental** [comment]
let karyn know when you start ticket @mkirolos-safco

**Comment by mkirolos-safco** [comment]
@kschaefges-safco , this is now on production, please let me know if you have any questions or concerns

**Comment by shreyadhutiasafcodental** [comment]
Email from Karyn: "Mario, 
A couple weeks ago, you implemented pixels for an October campaign we are starting tomorrow with a third party vendor.

Our partner recently tested the pixels firing and is following up with an issue. See below for explanation of issue and code for corrections. Can you update as soon as possible so that their team can test again? This is for a campaign we wanted to start tomorrow.

**Comment by shreyadhutiasafcodental** [comment]
Email from belmonrbusinessmedia "Hello Karyn,
Wanted to follow up with you regarding my request for copy to go along with your social campaign. See my previous email below for guidelines on that front. 

Our AdOps team got back to us with the following issue when testing your pixel placement. Please see below for their response:

“It looks like the deployed pixel has some additional elements.  Can you please have the client Paste the code directly from the text files”

EMG Provided Pixel: 
        <script src=[https://js.adsrvr.org/up_loader.1.1.0.js](https://url.us.m.mimecastprotect.com/s/CU35CjR9Aku73jotWf4CmR37d?domain=js.adsrvr.org) type="text/javascript"></script>
        <script type="text/javascript">
            ttd_dom_ready( function() {
                if (typeof TTDUniversalPixelApi === 'function') {
                    var universalPixelApi = new TTDUniversalPixelApi();
                    universalPixelApi.init("tybeo8i", ["8dqmvlv"], [https://insight.adsrvr.org/track/up](https://url.us.m.mimecastprotect.com/s/g1MKCkR06luMrn2UVhOCGfReW?domain=insight.adsrvr.org));
                }
            });
        </script>



Deployed Code:
<script type="text/javascript" id="">ttd_dom_ready(function(){if(typeof TTDUniversalPixelApi==="function"){var a=new TTDUniversalPixelApi;a.init("tybeo8i",["8dqmvlv"],[https://url.us.m.mimecastprotect.com/s/K0OWCKrVA2TJRwZixu0C5TfcM?domain\x3dinsight.adsrvr.org](https://url.us.m.mimecastprotect.com/s/GATPCADY82Ivn9pTG1ioCG5V8y?domain=insight.adsrvr.org))}});</script> 

Thank you"

**Comment by shreyadhutiasafcodental** [comment]
Waiting for 3rd party QA

**Comment by mkirolos-safco** [comment]
@kschaefges-safco , are we good with this ticket to mark it as completed.

**Comment by kschaefges-safco** [comment]
@mkirolos-safco , I have not heard back yet, if I don't hear this morning I will follow up.
