### ISSUE TITLE
[Feature]: WordPress Landing page Revisions - Jenn

### ISSUE THREAD

**Issue by mkirolos-safco** [Safco-Dental/Forms#95]
## Feature Request

**Title**: WordPress Landing page Revisions - Jenn

**Safco Employee Name**: Karyn Schaefges

**Safco Employee Email**: kschaefges@safcodental.com

**Department**: marketing

**Request Title**: WordPress Landing page Revisions - Jenn

**Short Description**:
 Ability to schedule to go live wordpress landing pages

**Benefits/Outcomes**: Having the ability to create landing pages for large events and to go live according to scheduled dates. This feature will allow pages created in advance and to not have to update on a daily basis the night before.

**Related Project**: main-website

**Priority**: high

**Request Completion Date**: 2024-10-15

**Comment by shreyadhutiasafcodental** [comment]
investigate @mkirolos-safco

**Comment by kschaefges-safco** [comment]
@mkirolos-safco we need to create one QR code for print piece, the code will link to one page that can be versioned and scheduled. What is the confidence level this can be done.

**Comment by mkirolos-safco** [comment]
I just had a call with Jenn and she is all set with this ticket, I will mark this one as completed accordingly!
